add verify secret exists in render deployment

diff --git a/.github/workflows/renderDeployment.yml b/.github/workflows/renderDeployment.yml
--- a/.github/workflows/renderDeployment.yml
+++ b/.github/workflows/renderDeployment.yml
@@ -11,6 +11,11 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@main #consider using pin for dependabot auto update
 
+      - name: Verify secrets exist
+        run: |
+          if [ -z "${{ secrets.RENDER_SERVICE_ID }}" ]; then echo "Missing service ID"; exit 1; fi
+          if [ -z "${{ secrets.RENDER_API_KEY }}" ]; then echo "Missing API key"; exit 1; fi
+
       - name: Create deployment
         uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
         with:
